require("anhyzer.remap")
require("anhyzer.settings")
require("anhyzer.lazy-bootstrap")
require("anhyzer.treesitter")
require("anhyzer.text")
require("anhyzer.telescope")
require("anhyzer.lsp")
require("anhyzer.autopair")
